version: '3'
services:
    node-watch:
        volumes:
            - ./node:/opt/project:rw
            - ./html:/opt/project/html:rw
            - ./services/watch/webpack.config.js:/opt/project/webpack.config.js:rw
        build:
            context: .
            dockerfile: services/watch/Dockerfile
        container_name: 6-20-23fa-watch
    apache-dev:
        volumes:
            - ./node/dev:/var/www/html/js:rw
            - ./html:/var/www/html:rw
            - ./www:/var/www:rw
        build:
            context: .
            dockerfile: services/apache/Dockerfile
        ports:
            - "8082:80"
        container_name: 6-20-23fa-dev
    apache-prod:
        volumes:
            - ./node/prod:/var/www/html/js:rw
            - ./html:/var/www/html:rw
            - ./www:/var/www:rw
        build:
            context: .
            dockerfile: services/apache/Dockerfile
        ports:
            - "8083:80"
        container_name: 6-20-23fa-prod